Repository clue/reactphp-buzz, pull requests merged in 2020-05, with the labels that each got.

#161 Explicitly close connection after response body ends
  src/Message/MessageFactory.php
  src/Message/ReadableBodyStream.php
  tests/FunctionalBrowserTest.php
  tests/Message/MessageFactoryTest.php
  tests/Message/ReadableBodyStreamTest.php
Labels: bug, new feature

#162 Use HTTP/1.1 protocol version by default and add new `Browser::withProtocolVersion()`
  README.md
  src/Browser.php
  src/Message/MessageFactory.php
  tests/BrowserTest.php
  tests/FunctionalBrowserTest.php
Labels: new feature

#163 Clean up test suite and add .gitattributes to exclude dev files from exports
  .gitattributes
  phpunit.xml.dist
Labels: easy pick, maintenance

#164 Fix cancellation of pending requests with promise followers
  src/Io/Transaction.php
  tests/FunctionalBrowserTest.php
  tests/Io/TransactionTest.php
Labels: bug
